version: '3.7'
services:
  devcontainer:
    image: bismuth/dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspaces:cached
      - /sys/fs/cgroup:/sys/fs/cgroup

    privileged: true
    cgroup: host

    command: /bin/sh -c "while sleep 1000; do :; done"

    ports:
      - "8000:8000"  # bismuthfe
      - "8001:8001"  # bismuthd - not strictly necessary to expose
      - "8002:8002"  # API

    networks:
      - app_network
