name: FaaS Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: faas/bismuthd/

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Rust
      run: |
        rustup toolchain install stable

    - name: Install Other Dependencies
      run: |
        sudo apt-get install -y curl clang pkg-config libssl-dev libfmt-dev protobuf-compiler containerd.io iptables iproute2

    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - name: Restore Build Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-debug
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build Debug
      run: |
        cargo build

    - name: Save Build Cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-debug

    - name: Start Test Services
      run: |
        docker compose up -d
        sleep 3

    - name: Unit Tests
      run: |
        CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='sudo -E' \
          RUST_BACKTRACE=1 \
          ZOOKEEPER_CLUSTER=localhost:2181 \
          cargo test --verbose

    - name: E2E Tests
      run: |
        sudo apt install -y python3 python3-pip
        pip3 install -r testing/requirements.txt

        ./target/debug/bismuthctl --zookeeper localhost:2181 bootstrap
        ./target/debug/bismuthctl --zookeeper localhost:2181 provision 127.0.0.1

        RUST_LOG=api=TRACE ./target/debug/api --zookeeper localhost:2181 &
        RUST_LOG=bismuthfe=TRACE ./target/debug/bismuthfe --zookeeper localhost:2181 &
        sudo RUST_LOG=bismuthd=TRACE ./target/debug/bismuthd --zookeeper localhost:2181 --bind 127.0.0.1 &

        sudo python3 testing/e2e.py
